# Generated by Django 3.1.5 on 2021-01-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
            ],
        ),
        migrations.AddField(
            model_name='imdbuser',
            name='recently_viewed',
            field=models.ManyToManyField(blank=True, related_name='recently_viewed', to='imdb_app.History'),
        ),
    ]
