# Generated by Django 3.1.5 on 2021-01-17 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0002_auto_20210117_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='movie_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
