# Generated by Django 3.1.5 on 2021-01-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0003_history_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='movie_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='title',
            field=models.CharField(max_length=350, unique=True),
        ),
    ]
